
import { Navbar } from '@/components';
import '@/styles/globals.css';
import { Lato } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-white scroll-pt-[100px] md:scroll-pt-[160px] text-primary' >
      <body className={lato.className}>
        <Toaster
          position="bottom-left"
          reverseOrder={false}
        />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
