export * from "./Logo";
export * from "./LogoText";
export * from "./Gine";
export * from "./Obstetricia";
export * from "./DeteccionVPH";
export * from "./TratamientoVPH";
export * from "./Mom";
export * from "./Facebook";
export * from "./Call";
export * from "./Wa";
export * from "./InstagramIcon";
export * from "./Navigate";
export * from "./PlusIcon";
export { ArrowDown } from "./ArrowDown";
export { DoctorIcon } from "./DoctorIcon";
export { DoctorIconWhite } from "./DoctorIconWhite";
